### ISSUE TITLE
positioning elements inside collection

### ISSUE THREAD

**Issue by JarekW** [fsi-open/admin-positionable-bundle#13]
To position elements inside collection we could add form type eg `collection_positionable` (or `position_sortable` maybe) that extends `collection`. This allows to theme all sortable collections and add javascript to handle moving items inside.

When sorted items are send, there need to be listener to `collection_positionable` that renumber models. Renumbering models require `Model/PositionableInterface` to have additional method `setPosition`.

To avoid BC there could be new interface `Model/Positionable` that adds `setPosition` method and mark old one as `@deprecated`. Probably this method will also be necessary in #8 

What do you think about that?

**Comment by chives** [comment]
Implemented in another bundle - https://github.com/fsi-open/form-extensions-bundle/pull/16
